.PHONY: clean All

All:
	@echo "----------Building project:[ Task - Debug ]----------"
	@cd "Task" && "$(MAKE)" -f  "Task.mk"
clean:
	@echo "----------Cleaning project:[ Task - Debug ]----------"
	@cd "Task" && "$(MAKE)" -f  "Task.mk" clean
